### PR TITLE
Move channels constants from utils.py to constants.py

### LINKED ISSUE #87: Move constant values
## Detailed Description
Would be great to move constant values (and duplicate) out of the code (functions) to somewhere easy to see. 

- Move list of channels in utils.py
- Move max and min of channels in utils.py

## Context
Keep code tidy

## Possible Implementation
Move to constants file.

### PR DESCRIPTION
**Pull request by JasonFengGit**
# Pull Request

## Description

Fixes #87

Moved channels lists and scalers from utils.py to constants.py

## How Has This Been Tested?

- [x] Yes
I tested with `pytest .`
Testing Results: 19 passed, 2 skipped, 107 warnings in 2072.94s (0:34:32)

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
Do you mind @JasonFengGit merging the latest release into your branch, this will mean that test will then run automatically

**Comment by JasonFengGit** [comment]
I just merged the latest release and I ran the tests on my local machine. tests on my machine says "19 passed, 2 skipped, 107 warnings in 2072.94s (0:34:32)".

**Comment by JasonFengGit** [comment]
Hi @peterdudfield @jacobbieker, the auto tests failed because of the API keys Environmental Variables, is there anything I can do to resolve this?

**Review by jacobbieker — APPROVED** [review]
This looks good to me! For the tests failing, I'm not sure if there is a way for us to give external PRs access to the secrets, unfortunately. This looks good though!

**Comment by JasonFengGit** [comment]
Thanks!

**Pull request merged**
