### PR TITLE
Update to Python 3.12

### PR DESCRIPTION
**Pull request by jacobbieker**
# Pull Request

## Description

Updates Satip to Python 3.12

Related to https://github.com/openclimatefix/ocf-infrastructure/issues/373

## How Has This Been Tested?

Unit tests

- [x] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by jacobbieker** [comment]
There seems to have been a change in Zarr that means that the attributes from Satpy now aren't valid to write into

**Comment by peterdudfield** [comment]
could you try python 3.11?

**Comment by peterdudfield** [comment]
That latest error is due to `coverage` not being the right version, need to upgrade it

**Comment by jacobbieker** [comment]
Ah okay, cool, was just about to ask that. What version does it need to be?

**Pull request merged**
