### PR TITLE
Run data tailor cleanup option

### PR DESCRIPTION
**Pull request by jacobbieker**
# Pull Request

## Description

Allows manually running the data tailor cleanup option in the app

Fixes #

## How Has This Been Tested?

Unit test

- [ ] Yes

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/nowcasting/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
Could you add an option so that we just run the clean up service?

**Comment by jacobbieker** [comment]
> Could you add an option so that we just run the clean up service?

Thats what this does, you ust pass `--cleanup True` to run cleanup and exit, otherwise pulls data

**Comment by jacobbieker** [comment]
You still have to login anyway to do it, so running cleanup logs in, runs the cleaning, and then returns without doing anything else

**Comment by peterdudfield** [comment]
> You still have to login anyway to do it, so running cleanup logs in, runs the cleaning, and then returns without doing anything else

Yea, so if you use that options it doesnt pull the data? and doesnt update s3?

**Comment by jacobbieker** [comment]
> > You still have to login anyway to do it, so running cleanup logs in, runs the cleaning, and then returns without doing anything else
> 
> Yea, so if you use that options it doesnt pull the data? and doesnt update s3?

Yeah, it only runs the cleanup, then exits. So running that won't affect anything else.

**Review by peterdudfield — APPROVED** [review]

**Pull request merged**
