### PR TITLE
Updated data test plotting scripts 

### LINKED ISSUE #231: Fix PR data test plotting script
## Describe the bug
The data plotting scripts located here: scripts/generate_test_plots.py are out of date and do not work anymore. They are very helpful for auto plotting data from the library on all PRs, checking if the data processing is still working right visually.

## Expected behavior
On PRs, the bot should add the plots automatically.

## Additional context
There is also a GitHub Action that would need to be updated.

### PR DESCRIPTION
**Pull request by suleman1412**
# Pull Request

## Description
Updated data test plotting scripts and created a new workflow for them
Fixes #231 

## How Has This Been Tested?
pytest

- [ ] Yes

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by suleman1412** [comment]
hi @jacobbieker I was able to run the script on local and managed to get the plots (attached is one of them)
image

I'm struggling with the new workflow, faced some dependency issues (some packages still don't support python 3.12), please let me know the further steps

**Review by jacobbieker — APPROVED** [review]
This looks really good! Thanks for getting it running again!

**Comment by jacobbieker** [comment]
If its ready to go, I am happy to merge it.

**Comment by peterdudfield** [comment]
@all-contributors please add @suleman1412  for code

**Pull request merged**
